### PR TITLE
Correct the coefficient in _calc_tau()

### LINKED ISSUE #65: Possible systematic offset from Gaussian normalization
I'm trying to benchmark pyspeckit against molsim and XCLASS.  I've made some progress, but I've found a systematic offset in the computed optical depths between XCLASS/pyseckit and molsim; the former are lower by a factor 1.064467, which is the ratio (2 pi / (8 log 2))^0.5 - i.e., the ratio of the normalization of the Gaussian integral to the FWMH/sigma ratio.

I think this indicates an error in molsim, but I'd like eyes on it.

The Gaussian line is here, and does not include any leading normalization factor:
https://github.com/bmcguir2/molsim/blob/master/molsim/utils.py#L69-L70

The tau calculation is here, and it's a lot harder to pin down exactly whether something could be missing:
https://github.com/bmcguir2/molsim/blob/master/molsim/classes.py#L1232-L1240
but I suspect `self.source.dV` is a FWHM and should be a `sigma` to be correct.

My derived tau in pyspeckit is also systematically different by a factor of v/c, but I believe this is a simple definitional choice; I calculate tau_nu, molsim calculates tau_v, so the systematic difference is expected.

The benchmarking notebook is here:
https://github.com/pyspeckit/pyspeckit-tests/blob/ce0aa614ef78d89db2f1f1b2767095ed1170f83c/xclass-benchmark/CO_Benchmark.ipynb

### PR DESCRIPTION
**Pull request by cixue**
Resolve #65 .

### CODE REVIEW

**Comment by bmcguir2** [comment]
Before merging in, I'd like to ask Adam to check that this fix brings molsim into alignment with pyspeckit/XCLASS.

**Comment by keflavich** [comment]
I'll have a look!

**Comment by keflavich** [comment]
perfect agreement now!  (all remaining disagreement is numerical noise in the n'th decimal place).  pyspeckit & molsim agree better than either agrees w/xclass.
image

**Comment by bmcguir2** [comment]
Fantastic, thanks folks.

**Pull request merged**
